const express=require("express");
const router=express.Router();
const jobController=require("../Controller/jobController");
router.get("/",jobController.getAllJobs);
router.get("/email",jobController.getJobsByEmail);
router.get("/:id",jobController.getJobById);
router.put("/:id",jobController.updateJobById);
router.post("/",jobController.createJob);
router.delete("/:id",jobController.deleteJob);
module.exports=router;